# Generated by Django 3.2.8 on 2021-10-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211006_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
