# Generated by Django 3.2.8 on 2021-10-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_related_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='Estoque'),
        ),
    ]
